/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "SYSTICK_interface.h"
#include "LCD_interface.h"
int main(void)
{
	MCAL_RCC_InitSysClock();
	MCAL_Rcc_EnablePrephiral(RCC_APB2_IOPAEN, RCC_APB2);
	MCAL_SYSTICK_vINIT();
	LCD_Init();
	LCD_SendString("LULU");
	LCD_Gotoyx(1, 0);
	LCD_SendString("Mohamed");
    /* Loop forever */
	for(;;)
	{
	}
}
