/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "STM32F103C8.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "GPT_interface.h"

int main(void)
{
	/*CLK INIT*/
	MCAL_RCC_InitSysClock();
	MCAL_Rcc_EnablePrephiral(RCC_APB2_TIM1EN, RCC_APB2);
	MCAL_Rcc_EnablePrephiral(RCC_APB2_IOPAEN, RCC_APB2);
	MCAL_GPIO_SetPinMode(GPIO_PORTA, GPIO_PIN1, GPIO_OUTPUT_LOW_SPEED_PUSHPULL);
	/*TIM 2 INIT*/
	GPT_Config_t Tim1_Config={1000,UPCounter,Edge_AllignedMode,DIV_1,Enable_Arr_Buffer,GPT_Enaple_Interrupt};
	GPT_TIMx_init(TIM1,&Tim1_Config);
	GPT_TIMx_SetPreScalar(TIM1,35999);
    /* Loop forever */
	for(;;)
	{
		MCAL_GPIO_SetPinValue(GPIO_PORTA, GPIO_PIN1, GPIO_HIGH);
		GPT_TIMx_SetBusyWait(TIM1, 1000, 1);
		MCAL_GPIO_SetPinValue(GPIO_PORTA, GPIO_PIN1, GPIO_LOW);
		GPT_TIMx_SetBusyWait(TIM1, 1000, 1);
	}
}
