/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
/*LIB*/
#include "STD_TYPES.h"
#include "BIT_MATH.h"
/*MCAL*/
#include "RCC_interface.h"
#include "GPIO_interface.h"


int main(void)
{
	/*Clk init*/
	Mcal_RCC_InitSysClock();
	Mcal_Rcc_EnablePrephiral(RCC_APB2_IOPAEN , RCC_APB2);
	/*OUTPUT*/
	Mcal_GPIO_SetPinMode(GPIO_PORTA, GPIO_PIN0, GPIO_OUTPUT_LOW_SPEED_PUSHPULL);
	Mcal_GPIO_SetPinValue(GPIO_PORTA, GPIO_PIN0, GPIO_HIGH);
	/*INPUT PULLUP*/
	Mcal_GPIO_SetPinMode(GPIO_PORTA, GPIO_PIN1, GPIO_INPUT_PULL_UP_MODE);
	Mcal_GPIO_SetPinValue(GPIO_PORTA, GPIO_PIN1, GPIO_HIGH);
	/* INPUT PULLDOWN default*/
	Mcal_GPIO_SetPinMode(GPIO_PORTA, GPIO_PIN2, GPIO_INPUT_PULL_DOWN_MODE);
	Mcal_GPIO_SetPinValue(GPIO_PORTA, GPIO_PIN2, GPIO_LOW);
    /* Loop forever */
	u8 Local_ReturnValue_1 = 0;
	u8 Local_ReturnValue_2 = 0;
	for(;;)
	{
		Mcal_GPIO_GetPinValue(GPIO_PORTA, GPIO_PIN1, &Local_ReturnValue_1);
		Mcal_GPIO_GetPinValue(GPIO_PORTA, GPIO_PIN2, &Local_ReturnValue_2);
	}

}
