/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include "STD_TYPES.h"
#include "BIT_MATH.h"
#include "RCC_interface.h"
#include "GPIO_interface.h"
#include "GPT_interface.h"

int main(void)
{
	MCAL_RCC_InitSysClock();
	MCAL_Rcc_EnablePrephiral(RCC_APB2_IOPAEN, RCC_APB2);
	MCAL_Rcc_EnablePrephiral(RCC_APB2_TIM1EN, RCC_APB2);
	MCAL_Rcc_EnablePrephiral(RCC_APB2_AFIOEN, RCC_APB2);
	MCAL_GPIO_SetPinMode(GPIO_PORTA, GPIO_PIN8, GPIO_OUTPUT_HIGH_SPEED_AF_PP);
	GPT_Config_t TIM1_config={.ARR=999
			,.ARB=Enable_Arr_Buffer
			,.Prescalar=31
			,.AllignMode=Edge_AllignedMode
			,.GPT_DIR=UPCounter
			,.INTState=GPT_Enaple_Interrupt
			,.CLK_Factor=DIV_1};
	GPT_TIMx_init(TIM1, &TIM1_config);
	GPT_PWM_Config_t TIM1_PWM_CONFIG ={
			.ARR=999,
			.Freq=1,
			.PWM_Channel=TIM_Channel1,
			.PWM_Mode=PWM_11
	};
	GPT_PWM_INIT(TIM1,&TIM1_PWM_CONFIG);
	GPT_PWM_SetDutyCycle(TIM1, TIM_Channel1, 50);
    /* Loop forever */
	for(;;)
	{
		for(u16 i=0;i<=100;i++)
		{
			GPT_PWM_SetDutyCycle(TIM1, TIM_Channel1, i);
		}
		for(u16 i=100;i>=0;i--)
		{
			GPT_PWM_SetDutyCycle(TIM1, TIM_Channel1, i);
		}
	}
}
